// ==UserScript==
// @name          Custom Yellow Theme for Perplexity AI
// @version       1.1
// @author        Spezi, 2023
// @description   Does no longer work because of highly specific autogenerated CSS-classnames (.hebEKa, .gnFpAY), which likely have changed.
// @attribution   Based on the PerplexityAI Dark Theme by 35e
// @match         https://*.perplexity.ai/*
// @grant         GM_xmlhttpRequest
// ==/UserScript==

(() => {
    'use strict';

    const cssUrl = 'https://raw.githubusercontent.com/35e/css-themes/main/perplexity.ai/theme.css';

    GM_xmlhttpRequest({
        method: 'GET',
        url: cssUrl,
        onload: function(response) {
            const style = document.createElement('style');
            style.textContent = response.responseText;
            document.head.appendChild(style);
        }
    });
})();
